In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

1) Create Two numpy array of size 3 X 2 and 2 X 3
2) Randomly Initalize that array

In [2]:
nparray1 = np.array([[3, 5], [5, 5], [6, 2]])
nparray2 = np.array([[9, 9 , 5], [8, 1, 4]])

3) Perform matrix multiplication

In [3]:
result1 = nparray1 @ nparray2        
print(result1)

[[67 32 35]
 [85 50 45]
 [70 56 38]]


4) Perform elementwise matrix multiplication

In [4]:
result2 = np.array([[0,0,0],
         [0,0,0],
         [0,0,0]])


for i in range(len(nparray1)):
   for j in range(len(nparray2[0])):
       for k in range(len(nparray2)):
           result2[i,j] += nparray1[i,k] * nparray2[k,j]


print(result2)

[[67 32 35]
 [85 50 45]
 [70 56 38]]


5) Find mean of first matrix

In [5]:
mean = np.mean(nparray1)
print(mean)

4.333333333333333


6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version

In [6]:
data=pd.read_csv('mtcars.csv')
arr1= np.array(data['mpg'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[ 0.909375  0.909375  2.709375  1.309375 -1.390625 -1.990625 -5.790625
  4.309375  2.709375 -0.890625 -2.290625 -3.690625 -2.790625 -4.890625
 -9.690625 -9.690625 -5.390625 12.309375 10.309375 13.809375  1.409375
 -4.590625 -4.890625 -6.790625 -0.890625  7.209375  5.909375 10.309375
 -4.290625 -0.390625 -5.090625  1.309375]


In [7]:
arr1= np.array(data['cyl'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[-0.1875 -0.1875 -2.1875 -0.1875  1.8125 -0.1875  1.8125 -2.1875 -2.1875
 -0.1875 -0.1875  1.8125  1.8125  1.8125  1.8125  1.8125  1.8125 -2.1875
 -2.1875 -2.1875 -2.1875  1.8125  1.8125  1.8125  1.8125 -2.1875 -2.1875
 -2.1875  1.8125 -0.1875  1.8125 -2.1875]


In [8]:
arr1= np.array(data['disp'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[ -70.721875  -70.721875 -122.721875   27.278125  129.278125   -5.721875
  129.278125  -84.021875  -89.921875  -63.121875  -63.121875   45.078125
   45.078125   45.078125  241.278125  229.278125  209.278125 -152.021875
 -155.021875 -159.621875 -110.621875   87.278125   73.278125  119.278125
  169.278125 -151.721875 -110.421875 -135.621875  120.278125  -85.721875
   70.278125 -109.721875]


In [9]:
arr1= np.array(data['hp'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[-36.6875 -36.6875 -53.6875 -36.6875  28.3125 -41.6875  98.3125 -84.6875
 -51.6875 -23.6875 -23.6875  33.3125  33.3125  33.3125  58.3125  68.3125
  83.3125 -80.6875 -94.6875 -81.6875 -49.6875   3.3125   3.3125  98.3125
  28.3125 -80.6875 -55.6875 -33.6875 117.3125  28.3125 188.3125 -37.6875]


In [10]:
arr1= np.array(data['drat'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[ 0.3034375  0.3034375  0.2534375 -0.5165625 -0.4465625 -0.8365625
 -0.3865625  0.0934375  0.3234375  0.3234375  0.3234375 -0.5265625
 -0.5265625 -0.5265625 -0.6665625 -0.5965625 -0.3665625  0.4834375
  1.3334375  0.6234375  0.1034375 -0.8365625 -0.4465625  0.1334375
 -0.5165625  0.4834375  0.8334375  0.1734375  0.6234375  0.0234375
 -0.0565625  0.5134375]


In [11]:
arr1= np.array(data['wt'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[-0.59725 -0.34225 -0.89725 -0.00225  0.22275  0.24275  0.35275 -0.02725
 -0.06725  0.22275  0.22275  0.85275  0.51275  0.56275  2.03275  2.20675
  2.12775 -1.01725 -1.60225 -1.38225 -0.75225  0.30275  0.21775  0.62275
  0.62775 -1.28225 -1.07725 -1.70425 -0.04725 -0.44725  0.35275 -0.43725]


In [12]:
arr1= np.array(data['qsec'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[-1.38875 -0.82875  0.76125  1.59125 -0.82875  2.37125 -2.00875  2.15125
  5.05125  0.45125  1.05125 -0.44875 -0.24875  0.15125  0.13125 -0.02875
 -0.42875  1.62125  0.67125  2.05125  2.16125 -0.97875 -0.54875 -2.43875
 -0.79875  1.05125 -1.14875 -0.94875 -3.34875 -2.34875 -3.24875  0.75125]


In [13]:
arr1= np.array(data['vs'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[-0.4375 -0.4375  0.5625  0.5625 -0.4375  0.5625 -0.4375  0.5625  0.5625
  0.5625  0.5625 -0.4375 -0.4375 -0.4375 -0.4375 -0.4375 -0.4375  0.5625
  0.5625  0.5625  0.5625 -0.4375 -0.4375 -0.4375 -0.4375  0.5625 -0.4375
  0.5625 -0.4375 -0.4375 -0.4375  0.5625]


In [14]:
arr1= np.array(data['am'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[ 0.59375  0.59375  0.59375 -0.40625 -0.40625 -0.40625 -0.40625 -0.40625
 -0.40625 -0.40625 -0.40625 -0.40625 -0.40625 -0.40625 -0.40625 -0.40625
 -0.40625  0.59375  0.59375  0.59375 -0.40625 -0.40625 -0.40625 -0.40625
 -0.40625  0.59375  0.59375  0.59375  0.59375  0.59375  0.59375  0.59375]


In [15]:
arr1= np.array(data['gear'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[ 0.3125  0.3125  0.3125 -0.6875 -0.6875 -0.6875 -0.6875  0.3125  0.3125
  0.3125  0.3125 -0.6875 -0.6875 -0.6875 -0.6875 -0.6875 -0.6875  0.3125
  0.3125  0.3125 -0.6875 -0.6875 -0.6875 -0.6875 -0.6875  0.3125  1.3125
  1.3125  1.3125  1.3125  1.3125  0.3125]


In [16]:
arr1= np.array(data['carb'])
nparrayCentered = arr1 - np.mean(arr1) 
print(nparrayCentered)

[ 1.1875  1.1875 -1.8125 -1.8125 -0.8125 -1.8125  1.1875 -0.8125 -0.8125
  1.1875  1.1875  0.1875  0.1875  0.1875  1.1875  1.1875  1.1875 -1.8125
 -0.8125 -1.8125 -1.8125 -0.8125 -0.8125  1.1875 -0.8125 -1.8125 -0.8125
 -0.8125  1.1875  3.1875  5.1875 -0.8125]
